# Generated by Django 4.2.27 on 2026-01-06 08:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('developer', models.CharField(blank=True, max_length=255, verbose_name='Разработчик')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Издатель')),
                ('imageUrl', models.URLField(blank=True, verbose_name='Обложка')),
                ('genres', models.CharField(blank=True, max_length=255, verbose_name='Жанры')),
                ('platforms', models.CharField(blank=True, max_length=255, verbose_name='Платформы')),
                ('steamAPIid', models.IntegerField(blank=True, null=True, verbose_name='Steam ID')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('steam', 'Steam'), ('epic', 'Epic Games'), ('gog', 'GOG')], max_length=100, verbose_name='Название')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Обычная цена')),
                ('discountPrice', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена со скидкой')),
                ('discountPercent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка в %')),
                ('currency', models.CharField(choices=[('USD', 'Доллар'), ('EUR', 'Евро'), ('RUB', 'Рубль')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('recordedAt', models.DateTimeField(auto_now_add=True, verbose_name='Время записи')),
                ('isLowest', models.BooleanField(default=False, verbose_name='Исторический минимум')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game', verbose_name='Игра')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'История цен',
                'ordering': ['-recordedAt'],
            },
        ),
    ]
