# Generated by Django 4.2.27 on 2026-01-17 14:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название')),
                ('itad_plain', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ITAD plain')),
                ('itad_id', models.UUIDField(null=True, unique=True)),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('developer', models.CharField(blank=True, max_length=512, verbose_name='Разработчик')),
                ('publisher', models.CharField(blank=True, max_length=512, verbose_name='Издатель')),
                ('image_url', models.URLField(blank=True, verbose_name='Обложка')),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lowest_price_currency', models.CharField(blank=True, default='USD', max_length=3, null=True)),
                ('genres', models.CharField(blank=True, max_length=512, verbose_name='Жанры (через запятую)')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itad_id', models.CharField(max_length=50, null=True, unique=True, verbose_name='ITAD shop id')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Обычная цена')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена со скидкой')),
                ('discount_percent', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка (%)')),
                ('is_history_low', models.BooleanField(null=True, verbose_name='Исторический минимум')),
                ('currency', models.CharField(choices=[('USD', 'Доллар'), ('EUR', 'Евро'), ('RUB', 'Рубль')], default='EUR', max_length=3, verbose_name='Валюта')),
                ('store_url', models.URLField(blank=True, verbose_name='Ссылка на магазин')),
                ('recorded_at', models.DateTimeField(verbose_name='Время записи')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.game', verbose_name='Игра')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'История цен',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['game', 'store'], name='core_priceh_game_id_cc9725_idx'), models.Index(fields=['discount_price'], name='core_priceh_discoun_58ba4d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(fields=('game', 'store', 'recorded_at'), name='unique_price_snapshot'),
        ),
    ]
