# Generated by Django 4.2.27 on 2026-01-07 09:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'История цены', 'verbose_name_plural': 'История цен'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='discountPrice',
            new_name='discount_price',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='recordedAt',
            new_name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='steamAPIid',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='discountPercent',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='isLowest',
        ),
        migrations.RemoveField(
            model_name='store',
            name='api_endpoint',
        ),
        migrations.AddField(
            model_name='game',
            name='itad_plain',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='ITAD plain'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='discount_percent',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='store_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на магазин'),
        ),
        migrations.AddField(
            model_name='store',
            name='itad_id',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='ITAD shop id'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.CharField(blank=True, max_length=255, verbose_name='Жанры (через запятую)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.CharField(blank=True, max_length=255, verbose_name='Платформы (windows, linux, mac)'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='currency',
            field=models.CharField(choices=[('USD', 'Доллар'), ('EUR', 'Евро'), ('RUB', 'Рубль')], default='EUR', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['game', 'store'], name='core_priceh_game_id_cc9725_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['discount_price'], name='core_priceh_discoun_58ba4d_idx'),
        ),
    ]
