# Generated by Django 4.2.27 on 2026-01-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_game_description_remove_game_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='itad_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
