# Generated by Django 4.2.27 on 2026-01-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_game_itad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='is_history_low',
            field=models.BooleanField(null=True, verbose_name='Исторический минимум'),
        ),
    ]
