# Generated by Django 4.2.27 on 2026-01-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pricehistory_is_history_low'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='itad_plain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ITAD plain'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
    ]
