# Generated by Django 4.2.27 on 2026-01-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_game_itad_plain_alter_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=512, verbose_name='Разработчик'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.CharField(blank=True, max_length=512, verbose_name='Жанры (через запятую)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=512, verbose_name='Издатель'),
        ),
    ]
