# Generated by Django 4.2.27 on 2026-01-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_game_developer_alter_game_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='recorded_at',
            field=models.DateTimeField(verbose_name='Время записи'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(fields=('game', 'store', 'recorded_at'), name='unique_price_snapshot'),
        ),
    ]
