# Generated by Django 4.2.27 on 2026-01-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pricehistory_recorded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lowest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='lowest_price_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='game',
            name='lowest_price_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store'),
        ),
    ]
