# Generated by Django 4.2.27 on 2026-01-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_game_lowest_price_game_lowest_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='lowest_price_store',
        ),
    ]
