# Generated by Django 4.2.27 on 2026-01-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_game_lowest_price_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='lowest_price_currency',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True),
        ),
    ]
